### ISSUE TITLE
Crash starting pg-boss in production

### ISSUE THREAD

**Issue by francisli** [francisli/streetpix-server#89]
```
2024-10-20T21:55:29.385911+00:00 app[web.1]: /app/node_modules/pg-pool/index.js:45
2024-10-20T21:55:29.385948+00:00 app[web.1]: Error.captureStackTrace(err)
2024-10-20T21:55:29.385949+00:00 app[web.1]: ^
2024-10-20T21:55:29.385950+00:00 app[web.1]: 
2024-10-20T21:55:29.385950+00:00 app[web.1]: error: no pg_hba.conf entry for host "54.147.81.85", user "u8gn0bm8192o1o", database "d9gc47qqbhvid2", no encryption
2024-10-20T21:55:29.385950+00:00 app[web.1]: at /app/node_modules/pg-pool/index.js:45:11
2024-10-20T21:55:29.385951+00:00 app[web.1]: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-10-20T21:55:29.385951+00:00 app[web.1]: at async Db.executeSql (/app/node_modules/pg-boss/src/db.js:42:14)
2024-10-20T21:55:29.385951+00:00 app[web.1]: at async Contractor.isInstalled (/app/node_modules/pg-boss/src/contractor.js:38:20)
2024-10-20T21:55:29.385952+00:00 app[web.1]: at async Contractor.start (/app/node_modules/pg-boss/src/contractor.js:43:23)
2024-10-20T21:55:29.385952+00:00 app[web.1]: at async PgBoss.start (/app/node_modules/pg-boss/src/index.js:121:7)
2024-10-20T21:55:29.385952+00:00 app[web.1]: at async Object.initialize (file:///app/server/lib/queue.js:18:3) {
2024-10-20T21:55:29.385952+00:00 app[web.1]: length: 172,
2024-10-20T21:55:29.385952+00:00 app[web.1]: severity: 'FATAL',
2024-10-20T21:55:29.385953+00:00 app[web.1]: code: '28000',
2024-10-20T21:55:29.385953+00:00 app[web.1]: detail: undefined,
2024-10-20T21:55:29.385953+00:00 app[web.1]: hint: undefined,
2024-10-20T21:55:29.385953+00:00 app[web.1]: position: undefined,
2024-10-20T21:55:29.385954+00:00 app[web.1]: internalPosition: undefined,
2024-10-20T21:55:29.385954+00:00 app[web.1]: internalQuery: undefined,
2024-10-20T21:55:29.385954+00:00 app[web.1]: where: undefined,
2024-10-20T21:55:29.385954+00:00 app[web.1]: schema: undefined,
2024-10-20T21:55:29.385954+00:00 app[web.1]: table: undefined,
2024-10-20T21:55:29.385955+00:00 app[web.1]: column: undefined,
2024-10-20T21:55:29.385955+00:00 app[web.1]: dataType: undefined,
2024-10-20T21:55:29.385955+00:00 app[web.1]: constraint: undefined,
2024-10-20T21:55:29.385955+00:00 app[web.1]: file: 'auth.c',
2024-10-20T21:55:29.385955+00:00 app[web.1]: line: '550',
2024-10-20T21:55:29.385955+00:00 app[web.1]: routine: 'ClientAuthentication'
2024-10-20T21:55:29.385956+00:00 app[web.1]: }
2024-10-20T21:55:29.385956+00:00 app[web.1]: 
```

**Comment by francisli** [comment]
Tried adding ssl=require in connection string, then got this error:

```
2024-10-20T22:00:38.493922+00:00 app[web.1]: /app/node_modules/pg/lib/connection.js:89
2024-10-20T22:00:38.493952+00:00 app[web.1]: if ('key' in self.ssl) {
2024-10-20T22:00:38.493953+00:00 app[web.1]: ^
2024-10-20T22:00:38.493953+00:00 app[web.1]: 
2024-10-20T22:00:38.493953+00:00 app[web.1]: TypeError: Cannot use 'in' operator to search for 'key' in require
2024-10-20T22:00:38.493954+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:89:19)
2024-10-20T22:00:38.493954+00:00 app[web.1]: at Object.onceWrapper (node:events:628:26)
2024-10-20T22:00:38.493954+00:00 app[web.1]: at Socket.emit (node:events:513:28)
2024-10-20T22:00:38.493954+00:00 app[web.1]: at addChunk (node:internal/streams/readable:324:12)
2024-10-20T22:00:38.493955+00:00 app[web.1]: at readableAddChunk (node:internal/streams/readable:297:9)
2024-10-20T22:00:38.493955+00:00 app[web.1]: at Readable.push (node:internal/streams/readable:234:10)
2024-10-20T22:00:38.493955+00:00 app[web.1]: at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2024-10-20T22:00:38.493956+00:00 app[web.1]: 
```
